apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  default.yaml: |-
    port: 3000
    loglevel: info
    persist: true
    dbname: echo
  # mongodburl: mongodb://root:password@my-mongo-mongodb-0.my-mongo-mongodb-headless.default.svc.cluster.local:27017,my-mongo-mongodb-1.my-mongo-mongodb-headless.default.svc.cluster.local:27017,my-mongo-mongodb-2.my-mongo-mongodb-headless.default.svc.cluster.local:27017/echo?authSource=admin&replicaSet=rs0

