apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    app: echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: us-central1-docker.pkg.dev/echo-hana/echoappregistry/echo_hana:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: config-vol
          mountPath: "/app/config"
          readOnly: true
      volumes:
      - name: config-vol
        configMap:
          name: mongodb-configmap
          items:
            - key: "default.yaml"
              path: "default.yaml"
